// Code generated by assets/generate_wire.py; DO NOT EDIT.
package kernel

import "unsafe"

const wireSchema = 3

type Snapshot struct {
	TimestampNS  uint64
	VQ           uint64
	KickFile     uint64
	Context      uint64
	Avail        uint64
	Used         uint64
	Backend      uint64
	Features     uint64
	WorkFlags    uint64
	Work         uint64
	Wait         uint64
	PollWQH      uint64
	ContextWQH   uint64
	Num          uint32
	EventID      uint32
	LastAvail    uint16
	LastUsed     uint16
	LittleEndian uint8
	Reserved     [3]uint8
	Schema       uint32
	Tail         [4]uint8
}

var _ [0 - int(unsafe.Offsetof(Snapshot{}.TimestampNS))]byte
var _ [int(unsafe.Offsetof(Snapshot{}.TimestampNS)) - 0]byte
var _ [8 - int(unsafe.Offsetof(Snapshot{}.VQ))]byte
var _ [int(unsafe.Offsetof(Snapshot{}.VQ)) - 8]byte
var _ [16 - int(unsafe.Offsetof(Snapshot{}.KickFile))]byte
var _ [int(unsafe.Offsetof(Snapshot{}.KickFile)) - 16]byte
var _ [24 - int(unsafe.Offsetof(Snapshot{}.Context))]byte
var _ [int(unsafe.Offsetof(Snapshot{}.Context)) - 24]byte
var _ [32 - int(unsafe.Offsetof(Snapshot{}.Avail))]byte
var _ [int(unsafe.Offsetof(Snapshot{}.Avail)) - 32]byte
var _ [40 - int(unsafe.Offsetof(Snapshot{}.Used))]byte
var _ [int(unsafe.Offsetof(Snapshot{}.Used)) - 40]byte
var _ [48 - int(unsafe.Offsetof(Snapshot{}.Backend))]byte
var _ [int(unsafe.Offsetof(Snapshot{}.Backend)) - 48]byte
var _ [56 - int(unsafe.Offsetof(Snapshot{}.Features))]byte
var _ [int(unsafe.Offsetof(Snapshot{}.Features)) - 56]byte
var _ [64 - int(unsafe.Offsetof(Snapshot{}.WorkFlags))]byte
var _ [int(unsafe.Offsetof(Snapshot{}.WorkFlags)) - 64]byte
var _ [72 - int(unsafe.Offsetof(Snapshot{}.Work))]byte
var _ [int(unsafe.Offsetof(Snapshot{}.Work)) - 72]byte
var _ [80 - int(unsafe.Offsetof(Snapshot{}.Wait))]byte
var _ [int(unsafe.Offsetof(Snapshot{}.Wait)) - 80]byte
var _ [88 - int(unsafe.Offsetof(Snapshot{}.PollWQH))]byte
var _ [int(unsafe.Offsetof(Snapshot{}.PollWQH)) - 88]byte
var _ [96 - int(unsafe.Offsetof(Snapshot{}.ContextWQH))]byte
var _ [int(unsafe.Offsetof(Snapshot{}.ContextWQH)) - 96]byte
var _ [104 - int(unsafe.Offsetof(Snapshot{}.Num))]byte
var _ [int(unsafe.Offsetof(Snapshot{}.Num)) - 104]byte
var _ [108 - int(unsafe.Offsetof(Snapshot{}.EventID))]byte
var _ [int(unsafe.Offsetof(Snapshot{}.EventID)) - 108]byte
var _ [112 - int(unsafe.Offsetof(Snapshot{}.LastAvail))]byte
var _ [int(unsafe.Offsetof(Snapshot{}.LastAvail)) - 112]byte
var _ [114 - int(unsafe.Offsetof(Snapshot{}.LastUsed))]byte
var _ [int(unsafe.Offsetof(Snapshot{}.LastUsed)) - 114]byte
var _ [116 - int(unsafe.Offsetof(Snapshot{}.LittleEndian))]byte
var _ [int(unsafe.Offsetof(Snapshot{}.LittleEndian)) - 116]byte
var _ [117 - int(unsafe.Offsetof(Snapshot{}.Reserved))]byte
var _ [int(unsafe.Offsetof(Snapshot{}.Reserved)) - 117]byte
var _ [120 - int(unsafe.Offsetof(Snapshot{}.Schema))]byte
var _ [int(unsafe.Offsetof(Snapshot{}.Schema)) - 120]byte
var _ [124 - int(unsafe.Offsetof(Snapshot{}.Tail))]byte
var _ [int(unsafe.Offsetof(Snapshot{}.Tail)) - 124]byte
var _ [128 - int(unsafe.Sizeof(Snapshot{}))]byte
var _ [int(unsafe.Sizeof(Snapshot{})) - 128]byte
