#!/usr/bin/env python3
"""Generate the private BPF wire declarations and compile-time offset checks."""
from pathlib import Path
root = Path(__file__).resolve().parent
fields = [
 ('timestamp_ns','TimestampNS','u64',0),('vq','VQ','u64',8),('kick_file','KickFile','u64',16),
 ('ctx','Context','u64',24),('avail','Avail','u64',32),('used','Used','u64',40),
 ('backend','Backend','u64',48),('features','Features','u64',56),('work_flags','WorkFlags','u64',64),
 ('work','Work','u64',72),('wait','Wait','u64',80),('poll_wqh','PollWQH','u64',88),('ctx_wqh','ContextWQH','u64',96),
 ('num','Num','u32',104),('eventfd_id','EventID','u32',108),('last_avail','LastAvail','u16',112),
 ('last_used','LastUsed','u16',114),('little_endian','LittleEndian','u8',116),('reserved','Reserved','pad3',117),
 ('schema','Schema','u32',120),('tail','Tail','pad4',124)]
c={'u64':'unsigned long long','u32':'unsigned int','u16':'unsigned short','u8':'unsigned char','pad3':'unsigned char','pad4':'unsigned char'}
g={'u64':'uint64','u32':'uint32','u16':'uint16','u8':'uint8','pad3':'[3]uint8','pad4':'[4]uint8'}
h=['/* Code generated by generate_wire.py; DO NOT EDIT. */','#ifndef VHOST_WIRE_H','#define VHOST_WIRE_H','#define VHOST_WIRE_SCHEMA 2','struct snapshot {']
go=['// Code generated by assets/generate_wire.py; DO NOT EDIT.','package kernel','import "unsafe"','const wireSchema = 2','type Snapshot struct {']
for cn,gn,t,off in fields:
 h.append(f'    {c[t]} {cn}'+('['+t[3:]+']' if t.startswith('pad') else '')+';')
 go.append(f'    {gn} {g[t]}')
h+=['};','_Static_assert(sizeof(struct snapshot) == 128, "snapshot size");']
go+=['}']
for cn,gn,t,off in fields:
 h.append(f'_Static_assert(__builtin_offsetof(struct snapshot, {cn}) == {off}, "{cn} offset");')
 go.extend([f'var _ [{off}-int(unsafe.Offsetof(Snapshot{{}}.{gn}))]byte',f'var _ [int(unsafe.Offsetof(Snapshot{{}}.{gn}))-{off}]byte'])
go.extend(['var _ [128-int(unsafe.Sizeof(Snapshot{}))]byte','var _ [int(unsafe.Sizeof(Snapshot{}))-128]byte'])
counter=['signals','writes','wakeups','handlers','last_signal_ns','last_write_ns','last_wakeup_ns','last_handler_ns','active','epoch']
h+=['struct counters {']+[f'    unsigned long long {x};' for x in counter]+['};','_Static_assert(sizeof(struct counters) == 80, "counter size");','#endif','']
(root/'wire.h').write_text('\n'.join(h))
(root.parent/'wire_generated.go').write_text('\n'.join(go)+'\n')
