/* Code generated by generate_wire.py; DO NOT EDIT. */
#ifndef VHOST_WIRE_H
#define VHOST_WIRE_H
#define VHOST_WIRE_SCHEMA 3
struct snapshot {
    unsigned long long timestamp_ns;
    unsigned long long vq;
    unsigned long long kick_file;
    unsigned long long ctx;
    unsigned long long avail;
    unsigned long long used;
    unsigned long long backend;
    unsigned long long features;
    unsigned long long work_flags;
    unsigned long long work;
    unsigned long long wait;
    unsigned long long poll_wqh;
    unsigned long long ctx_wqh;
    unsigned int num;
    unsigned int eventfd_id;
    unsigned short last_avail;
    unsigned short last_used;
    unsigned char little_endian;
    unsigned char reserved[3];
    unsigned int schema;
    unsigned char tail[4];
};
_Static_assert(sizeof(struct snapshot) == 128, "snapshot size");
_Static_assert(__builtin_offsetof(struct snapshot, timestamp_ns) == 0, "timestamp_ns offset");
_Static_assert(__builtin_offsetof(struct snapshot, vq) == 8, "vq offset");
_Static_assert(__builtin_offsetof(struct snapshot, kick_file) == 16, "kick_file offset");
_Static_assert(__builtin_offsetof(struct snapshot, ctx) == 24, "ctx offset");
_Static_assert(__builtin_offsetof(struct snapshot, avail) == 32, "avail offset");
_Static_assert(__builtin_offsetof(struct snapshot, used) == 40, "used offset");
_Static_assert(__builtin_offsetof(struct snapshot, backend) == 48, "backend offset");
_Static_assert(__builtin_offsetof(struct snapshot, features) == 56, "features offset");
_Static_assert(__builtin_offsetof(struct snapshot, work_flags) == 64, "work_flags offset");
_Static_assert(__builtin_offsetof(struct snapshot, work) == 72, "work offset");
_Static_assert(__builtin_offsetof(struct snapshot, wait) == 80, "wait offset");
_Static_assert(__builtin_offsetof(struct snapshot, poll_wqh) == 88, "poll_wqh offset");
_Static_assert(__builtin_offsetof(struct snapshot, ctx_wqh) == 96, "ctx_wqh offset");
_Static_assert(__builtin_offsetof(struct snapshot, num) == 104, "num offset");
_Static_assert(__builtin_offsetof(struct snapshot, eventfd_id) == 108, "eventfd_id offset");
_Static_assert(__builtin_offsetof(struct snapshot, last_avail) == 112, "last_avail offset");
_Static_assert(__builtin_offsetof(struct snapshot, last_used) == 114, "last_used offset");
_Static_assert(__builtin_offsetof(struct snapshot, little_endian) == 116, "little_endian offset");
_Static_assert(__builtin_offsetof(struct snapshot, reserved) == 117, "reserved offset");
_Static_assert(__builtin_offsetof(struct snapshot, schema) == 120, "schema offset");
_Static_assert(__builtin_offsetof(struct snapshot, tail) == 124, "tail offset");
struct counters {
    unsigned long long signals;
    unsigned long long writes;
    unsigned long long wakeups;
    unsigned long long handlers;
    unsigned long long last_signal_ns;
    unsigned long long last_write_ns;
    unsigned long long last_wakeup_ns;
    unsigned long long last_handler_ns;
    unsigned long long active;
    unsigned long long epoch;
};
_Static_assert(sizeof(struct counters) == 80, "counter size");
#endif
